# Generated by Django 4.2.5 on 2023-10-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_Name', models.CharField(max_length=100)),
                ('power_Of_Load', models.IntegerField(default=0)),
                ('operating_Hours', models.IntegerField(default=0)),
                ('no_Of_Load', models.IntegerField(default=0)),
                ('effective_Sunlight', models.IntegerField(default=0)),
                ('userD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Inputs',
            },
        ),
    ]
