# Generated by Django 4.2.5 on 2023-10-03 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp1', '0002_userinput'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinput',
            table='UserInput',
        ),
    ]
