# Generated by Django 4.2.5 on 2023-10-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp1', '0003_alter_userinput_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinput',
            table=None,
        ),
    ]
