# Generated by Django 4.2.5 on 2023-10-09 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp1', '0004_alter_userinput_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='userD',
        ),
        migrations.AddField(
            model_name='userinput',
            name='userD',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
