# Generated by Django 4.2.5 on 2023-10-25 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp1', '0005_remove_userinput_userd_userinput_userd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronicName', models.CharField(max_length=100)),
                ('power_Of_Load', models.IntegerField(default=0)),
                ('operating_Hours', models.IntegerField(default=0)),
                ('no_Of_Load', models.IntegerField(default=0)),
                ('effective_Sunlight', models.IntegerField(default=0)),
                ('userF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
